version: '3.7'
services:
  frontend:
    build: ./frontend
    container_name: "nodejs"
#    volumes:
#     - "./frontend/ujiyamada_project_2022/public:/var/www/html"
    privileged: true
    ports:
      - "4000:4001"
    networks:
      - ujiyamada_project_2022_default
    depends_on:
      - apache

  backend:
    build: ./backend
    container_name: "apache"
    volumes:
      - "./html/:/var/www/html"
    privileged: true
    ports:
      - "80:80"
    networks:
      - ujiyamada_project_2022_default
    depends_on:
      - mysql

  mysql:
    build: ./db
    container_name: db-container
    volumes:
      - .db/mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
    ports:
      - "4306:3306"
    networks:
      - ujiyamada_project_2022_default
