version: '3.7'
services:
  web:
    build: .
    container_name: "apache"
    volumes:
      - "./html/:/var/www/html"
    privileged: true
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    ports:
      - "4306:3306"
    container_name: mysql8-1