version: '3.7'
services:

  backend:
    build: ./
    container_name: php-container
    privileged: true
    ports:
      - "8080:80"
    depends_on:
      - mysql
    tty: true
      
  mysql:
    build: ./db/
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

    restart: always
    
