version: '3.8'
services:
  app:
    container_name: nkc-cloud-app
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/src
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR-USEPOLLING=true
